export default {
  CREATE: 'trax/song-player/CREATE',
  PLAY: 'trax/song-player/PLAY',
  PAUSE: 'trax/song-player/PAUSE',
  STOP: 'trax/song-player/STOP',
  RESTART: 'trax/song-player/RESTART',
  TOGGLE_PLAY: 'trax/song-player/TOGGLE_PLAY',
  TICK: 'trax/song-player/TICK',
  REVERSE_TICK: 'trax/song-player/REVERSE_TICK',
  SET_LOOP: 'trax/song-player/SET_LOOP',
  TOGGLE_LOOP: 'trax/song-player/TOGGLE_LOOP',
  SET_BEAT_DURATION: 'trax/song-player/SET_BEAT_DURATION',
  SET_CURRENT_BEAT: 'trax/song-player/SET_CURRENT_BEAT',
  SET_CURRENT_SONG: 'trax/song-player/SET_CURRENT_SONG',
  CLEAR_CURRENT_SONG: 'trax/song-player/CLEAR_CURRENT_SONG',
}
